# Generated by Django 4.1.2 on 2023-02-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_rpc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstats',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productstats',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
