# Generated by Django 4.1.2 on 2023-02-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_rpc', '0002_alter_orderstats_created_alter_productstats_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstats',
            name='client_id',
            field=models.BigIntegerField(),
        ),
    ]
