# Generated by Django 4.1.2 on 2023-07-14 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_rpc', '0003_alter_productstats_client_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fk_product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_maps', to='product_rpc.productcategory')),
            ],
            options={
                'db_table': 'rpc_weight_map',
            },
        ),
    ]
