# Generated by Django 4.1.2 on 2023-08-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_rpc', '0003_alter_productstats_client_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_category_id', models.IntegerField(blank=True)),
                ('weight', models.DecimalField(decimal_places=4, max_digits=9)),
            ],
            options={
                'db_table': 'rpc_weight_map',
            },
        ),
    ]
