# Generated by Django 5.1.7 on 2025-04-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_rpc', '0006_report_db_target_reportparam_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='db_target',
            field=models.CharField(choices=[('odoo_v11', 'odoo_v11'), ('odoo_v15', 'odoo_v15'), ('odoo_v17', 'odoo_v17')], default='odoo_v17', max_length=20),
        ),
    ]
