# Generated by Django 4.1.2 on 2023-02-25 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PosSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pos_name', models.CharField(max_length=50)),
                ('odoo_session_id', models.IntegerField()),
                ('odoo_cash', models.IntegerField()),
                ('odoo_card', models.IntegerField()),
                ('pos_cash', models.IntegerField()),
                ('pos_card', models.IntegerField()),
                ('profit_total', models.IntegerField()),
                ('balance_start', models.IntegerField()),
                ('balance_start_next_day', models.IntegerField()),
                ('session_name', models.CharField(max_length=100)),
                ('start_at', models.DateTimeField()),
                ('stop_at', models.DateTimeField()),
                ('end_state', models.CharField(choices=[('EX', 'Extra'), ('ST', 'Stable'), ('MS', 'Missing')], default='ST', max_length=2)),
                ('end_state_note', models.TextField()),
                ('end_state_amount', models.IntegerField()),
                ('json', models.TextField()),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier', to='pos_close_control.employee')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='pos_close_control.employee')),
            ],
        ),
    ]
