# Generated by Django 4.1.2 on 2023-02-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_close_control', '0002_alter_possession_balance_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possession',
            name='balance_start',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='possession',
            name='balance_start_next_day',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='possession',
            name='end_state_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='possession',
            name='odoo_card',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='possession',
            name='odoo_cash',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='possession',
            name='pos_card',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='possession',
            name='pos_cash',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='possession',
            name='profit_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
