# Generated by Django 4.1.2 on 2023-03-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_close_control', '0003_alter_possession_balance_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[('CA', 'CA'), ('MN', 'MN')], default='CA', max_length=2),
        ),
    ]
