# Generated by Django 4.2.4 on 2023-11-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_close_control', '0006_possession_odoo_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possession',
            name='balance_start',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='possession',
            name='balance_start_next_day',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='possession',
            name='end_state_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='possession',
            name='odoo_card',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='possession',
            name='odoo_cash',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='possession',
            name='pos_card',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='possession',
            name='pos_cash',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='possession',
            name='profit_total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
