# Generated by Django 4.2.4 on 2025-03-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_close_control', '0007_alter_possession_balance_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possession',
            name='odoo_version',
            field=models.IntegerField(default=17),
        ),
    ]
