# Generated by Django 5.1.6 on 2025-03-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_close_control', '0007_alter_possession_balance_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='possession',
            name='odoo_config_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='possession',
            name='odoo_version',
            field=models.IntegerField(default=17),
        ),
    ]
