# Generated by Django 4.2.4 on 2025-03-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_close_control', '0008_alter_possession_odoo_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='possession',
            name='odoo_config_id',
            field=models.IntegerField(default=0),
        ),
    ]
