# Generated by Django 5.1.6 on 2025-03-09 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_close_control', '0008_alter_possession_odoo_version'),
        ('pos_close_control', '0008_possession_odoo_config_id_and_more'),
    ]

    operations = [
    ]
