# Generated by Django 4.2.4 on 2026-01-10 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos_close_control', '0009_possession_odoo_config_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosSessionV2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pos_name', models.CharField(max_length=50)),
                ('odoo_session_id', models.IntegerField()),
                ('odoo_config_id', models.IntegerField(default=0)),
                ('odoo_cash', models.IntegerField()),
                ('odoo_card', models.IntegerField()),
                ('pos_cash', models.IntegerField()),
                ('pos_card', models.IntegerField()),
                ('profit_total', models.IntegerField()),
                ('balance_start', models.IntegerField()),
                ('balance_start_next_day', models.IntegerField()),
                ('session_name', models.CharField(max_length=100)),
                ('start_at', models.DateTimeField()),
                ('stop_at', models.DateTimeField()),
                ('end_state', models.CharField(choices=[('EX', 'Extra'), ('ST', 'Stable'), ('MS', 'Missing')], default='ST', max_length=2)),
                ('end_state_note', models.TextField()),
                ('end_state_amount', models.IntegerField()),
                ('json', models.TextField()),
                ('odoo_version', models.IntegerField(default=17)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_v2', to='pos_close_control.employee')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_v2', to='pos_close_control.employee')),
            ],
        ),
    ]
