# Generated by Django 4.2.4 on 2026-01-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_close_control', '0010_possessionv2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possessionv2',
            name='stop_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
