# Generated by Django 4.2.4 on 2026-01-15 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos_close_control', '0011_alter_possessionv2_stop_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possessionv2',
            name='balance_start_next_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='possessionv2',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashier_v2', to='pos_close_control.employee'),
        ),
        migrations.AlterField(
            model_name='possessionv2',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_v2', to='pos_close_control.employee'),
        ),
    ]
