# Generated by Django 4.2.4 on 2026-01-15 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos_close_control', '0012_alter_possessionv2_balance_start_next_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='possessionv2',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('CL', 'Closed')], default='DR', max_length=2),
        ),
        migrations.CreateModel(
            name='PosSessionV2Snapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_session_id', models.IntegerField()),
                ('snapshot_created_at', models.DateTimeField(auto_now_add=True)),
                ('pos_name', models.CharField(max_length=50)),
                ('odoo_session_id', models.IntegerField()),
                ('odoo_config_id', models.IntegerField()),
                ('odoo_cash', models.IntegerField()),
                ('odoo_card', models.IntegerField()),
                ('pos_cash', models.IntegerField()),
                ('pos_card', models.IntegerField()),
                ('profit_total', models.IntegerField()),
                ('balance_start', models.IntegerField()),
                ('balance_start_next_day', models.IntegerField()),
                ('session_name', models.CharField(max_length=100)),
                ('start_at', models.DateTimeField()),
                ('stop_at', models.DateTimeField(blank=True, null=True)),
                ('end_state', models.CharField(max_length=2)),
                ('end_state_note', models.TextField()),
                ('end_state_amount', models.IntegerField()),
                ('json', models.TextField()),
                ('status', models.CharField(max_length=2)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_cashier_v2', to='pos_close_control.employee')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_manager_v2', to='pos_close_control.employee')),
            ],
        ),
    ]
