# Generated by Django 4.2.4 on 2026-01-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_close_control', '0014_alter_possessionv2_end_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possessionv2snapshot',
            name='end_state',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='possessionv2snapshot',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
