# Generated by Django 4.2.4 on 2026-01-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_close_control', '0015_alter_possessionv2snapshot_end_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possessionv2snapshot',
            name='end_state',
            field=models.CharField(choices=[('EXTRA', 'Extra'), ('STABLE', 'Stable'), ('MISSING', 'Missing')], default='STABLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='possessionv2snapshot',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10),
        ),
    ]
