# Generated by Django 4.2.28 on 2026-06-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_close_control', '0017_employee_totp_secret_otpsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='store',
            field=models.CharField(choices=[('san martin', 'san martin'), ('abtao', 'abtao'), ('tingo maria', 'tingo maria')], default='abtao', max_length=15),
        ),
    ]
