# Generated by Django 5.1.7 on 2025-04-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PosExternalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_data', models.TextField(verbose_name='Datos de Orden')),
                ('user_name', models.TextField(blank=True, null=True)),
                ('config_name', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Éxito'), ('error', 'Error')], max_length=20, verbose_name='Estado')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Respuesta API')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Registro de Integración POS',
                'verbose_name_plural': 'Registros de Integración POS',
            },
        ),
    ]
