ACCESSORIES = "ACCESSORIES"
MEN = "MEN"
WOMEN = "WOMEN"
SPORTS = "SPORTS"
HOME = "HOME"
CHILDREN = "CHILDREN"
CLEARANCE = "CLEARANCE"
MISCELLANEOUS = "MISCELLANEOUS"

EQ_CHOICES = [
    (ACCESSORIES, ACCESSORIES),
    (MEN, MEN),
    (WOMEN, WOMEN),
    (SPORTS, SPORTS),
    (HOME, HOME),
    (CHILDREN, CHILDREN),
    (CLEARANCE, CLEARANCE),
    (MISCELLANEOUS, MISCELLANEOUS),
]

STORE_SAN_MARTIN = "san martin"
STORE_ABTAO = "abtao"
STORE_TINGO_MARIA = "tingo maria"

STORE_CHOICES = [
    (STORE_SAN_MARTIN, STORE_SAN_MARTIN),
    (STORE_ABTAO, STORE_ABTAO),
    (STORE_TINGO_MARIA, STORE_TINGO_MARIA),
]
