ACCESSORIES = "ACCESSORIES"
MEN = "MEN"
WOMEN = "WOMEN"
SPORTS = "SPORTS"
HOME = "HOME"
CHILDREN = "CHILDREN"
CLEARANCE = "CLEARANCE"
MISCELLANEOUS = "MISCELLANEOUS"

EQ_CHOICES = [
    (ACCESSORIES, ACCESSORIES),
    (MEN, MEN),
    (WOMEN, WOMEN),
    (SPORTS, SPORTS),
    (HOME, HOME),
    (CHILDREN, CHILDREN),
    (CLEARANCE, CLEARANCE),
    (MISCELLANEOUS, MISCELLANEOUS),
]
