# Generated by Django 4.2.4 on 2024-02-02 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supervisor', models.CharField(max_length=50)),
                ('section_name', models.CharField(choices=[('ACCESSORIES', 'ACCESSORIES'), ('MEN', 'MEN'), ('WOMEN', 'WOMEN'), ('SPORTS', 'SPORTS'), ('HOME', 'HOME'), ('CHILDREN', 'CHILDREN'), ('CLEARANCE', 'CLEARANCE'), ('MISCELLANEOUS', 'MISCELLANEOUS')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StoreSectionGoal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('goal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_sections', to='miscellaneous.storesection')),
            ],
            options={
                'unique_together': {('year', 'month', 'section')},
            },
        ),
    ]
