# Generated by Django 4.2.4 on 2024-08-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreGoal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('goal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('store', models.CharField(choices=[('san martin', 'san martin'), ('abtao', 'abtao'), ('tingo maria', 'tingo maria')], max_length=15)),
            ],
        ),
    ]
