REPORT_FIELDTYPE_DATE = "date"
REPORT_FIELDTYPE_TEXT = "text"
REPORT_FIELDTYPE_NUMBER = "number"

REPORT_DATATYPE_CHOICES = [
    (REPORT_FIELDTYPE_DATE, REPORT_FIELDTYPE_DATE),
    (REPORT_FIELDTYPE_TEXT, REPORT_FIELDTYPE_TEXT),
    (REPORT_FIELDTYPE_NUMBER, REPORT_FIELDTYPE_NUMBER),
]
